// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rxvcxqfnkvqfxwzbujka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dmN4cWZua3ZxZnh3emJ1amthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NTcwNjcsImV4cCI6MjA4NDQzMzA2N30.kWB2Hkvthei5Jn4k4ex6txfofVms5qCjZ5e9aArSf5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);